spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/testmybatis?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  thymeleaf:
    cache: false
mybatis:
  type-aliases-package: com.zyfgoup.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
#server:
#  servlet:
#    context-path: /CRUDDemo
